name: dukascopy
description: A Dart wrapper for fetching data from Dukascopy Bank SA API.


repository: https://github.com/Erhabor-Fona/dukascopy
homepage: https://github.com/Erhabor-Fona/dukascopy


environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:


  http: ^1.3.0
  intl: ^0.20.2


  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
